organizer/urls.py
from django.conf.urls import url
from . import views

app_name = 'organizer'

urlpatterns = [
    url(r'^$', views.index, name='index'),
	url(r'^create_trip/$', views.create_trip, name='create_trip'),
	url(r'^compare/$', views.compare, name='compare'),
	url(r'^(?P<trip_id>[0-9]+)/delete_trip/$', views.delete_trip, name='delete_trip'),
	
	url(r'^register/$', views.register_with_activation, name='register'),
	url(r'^activate/(?P<key>.+)$', views.activate, name='activate'),
	url(r'^login/$', views.login_user, name='login_user'),
	url(r'^logout_user/$', views.logout_user, name='logout_user'),
	url(r'^trip/(?P<trip_id>[0-9]+)/$', views.details2, name='detail'),
	
	
	url(r'^trip/(?P<trip_id>[0-9]+)/date_change$', views.date_change, name='date_change'),
	url(r'^trip/(?P<trip_id>[0-9]+)/hotel_change$', views.hotel_change, name='hotel_change'),
	url(r'^trip/(?P<trip_id>[0-9]+)/flight_change$', views.flight_change, name='flight_change'),
	url(r'^trip/(?P<trip_id>[0-9]+)/transport_change$', views.transport_change, name='transport_change'),
	url(r'^trip/(?P<trip_id>[0-9]+)/add_flight$', views.add_flight, name='add_flight'),
	
	url(r'^trip/(?P<trip_id>[0-9]+)/add_node$', views.add_node, name='add_node'),
	url(r'^trip/(?P<trip_id>[0-9]+)/insert_node$', views.insert_node, name='insert_node'),
	url(r'^trip/(?P<trip_id>[0-9]+)/node_edit$', views.node_edit, name='node_edit'),
	url(r'^trip/(?P<trip_id>[0-9]+)/node_edit_json$', views.node_edit_json, name='node_edit_json'),
	url(r'^trip/(?P<trip_id>[0-9]+)/node_delete$', views.node_delete, name='node_delete'),
	url(r'^trip/(?P<trip_id>[0-9]+)/share$', views.share, name='share'),
	
	
]

travelSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^organizer/', include('organizer.urls')),
	url(r'^', include('organizer.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organizer/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Trip, NewTrip

class TripForm(forms.ModelForm):

	class Meta:
		model = Trip
		
		fields = [
			'startDate',
			'endDate',
			'trip_type',
			'destination',
			'trip_picture',
			'hotel',
			'hotel_price',
			'existing_hotel',
			'existing_hotel_price',
			'flight_no',
			'flight_price',
			'transport_company', 
			'transport_price',
		]
		
		widgets = {
            'startDate': forms.DateInput(attrs={'class':'date'}),
            'endDate': forms.DateInput(attrs={'class':'date'}),
        }

	def clean(self):
		
		data = super(TripForm, self).clean()
		print(data)
		startDate = data.get('startDate')
		endDate = data.get('endDate')
		if endDate and startDate:
			print('got start and end dates')
			if  not (endDate > startDate):
				print('raising Error')
				raise forms.ValidationError('endDate must be after startDate')
				
		

		return data


		
		
class NewCreateTripForm(forms.ModelForm):
	class Meta:
		model = NewTrip
		
		fields = [
			'startDate',
			'endDate',
			'trip_type',
			'destination',
			'trip_picture',
		]
		
		widgets = {
            'startDate': forms.DateInput(attrs={'class':'date'}),
            'endDate': forms.DateInput(attrs={'class':'date'}),
        }
		
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
		
		
		
class MyRegistrationForm(UserCreationForm):
    email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')        

    def save(self,commit = True):   
        user = super(MyRegistrationForm, self).save(commit = False)
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()

        return user		
		

organizer/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, JsonResponse
from django.template import loader
from .forms import  UserForm, TripForm, NewCreateTripForm, MyRegistrationForm
from .models import Trip, Flight, TripType, Hotel, NewTrip, Node, NodeType, ActivationKey
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.views.generic import View
from datetime import datetime
from django.core.urlresolvers import reverse
import decimal
from django.contrib import messages
from django.core import serializers
import json
from django.template.loader import render_to_string
import requests
import hashlib
import random
from django.db.models import Q, Sum, F, Count
from itertools import chain
from django.template.defaulttags import register



# Create your views here.

def create_trip(request):
	print("inside create view ")
	if not request.user.is_authenticated():
		return render(request, 'organizer/login.html')
	else:
		form = NewCreateTripForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			trip = form.save(commit=False)
			trip.user = request.user
			trip.save()
			return redirect(reverse('organizer:detail', kwargs={'trip_id' :   trip.pk}), request)
		
		trip_types = TripType.objects.all()
		context = {
			"form": form,
			"trip_types" : trip_types,
			'loged_user': request.user
		}
		return render(request, 'organizer/create_new_trip.html', context)

@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)
		
def compare(request):
	print(request.GET.get("trips"))
	loged_user = request.user
	if request.GET.get("trips"):
		trips_ids = request.GET.get("trips").split(",")
		trips_ids = filter(None, trips_ids)
		trips_ids= list(map(int, trips_ids))
		trips = NewTrip.objects.filter(id__in=trips_ids)
		prices = {}
		for trip in trips:
			sum = Node.objects.filter(trip=trip.pk).aggregate(Sum('price'))
			prices[trip.pk] = sum['price__sum']
		print(prices)
		loged_user = request.user
	
		context = {'trips': trips, 'prices':prices, 'loged_user':loged_user}
	
		return render(request, 'organizer/compare.html', context)
	return render(request, 'organizer/error.html', {'error': 'You did not choose any trips to compare', 'loged_user':loged_user})
		
def delete_trip(request, trip_id):
	if not request.user.is_authenticated():
		return render(request, 'organizer/login.html')
	try:
		trip = NewTrip.objects.get(pk=trip_id, user=request.user)
		if trip is not None:
			trip.delete()
	except (KeyError, NewTrip.DoesNotExist):
		pass
	return redirect('/organizer/', request)


def search(all_shared_trips, query=""):
	context = {}
	all_shared_trips = all_shared_trips.filter(
		Q(destination__icontains=query) |
		Q(trip_type__type_name__icontains=query)
		)
	context['search_value'] = query
	context['all_shared_trips'] = all_shared_trips
	print(context)
	return context
		

def index(request):
	if not request.user.is_authenticated():
		
		all_shared_trips = NewTrip.objects.filter(shared=True)
		
		if request.method == "GET":
			query = request.GET.get('q')
			if query:
				return render(request, 'organizer/index.html', search(all_shared_trips, query) )
		return render(request, 'organizer/index.html', search(all_shared_trips) )
	else:
		all_shared_trips = NewTrip.objects.filter(shared=True)
		context = {'all_shared_trips': all_shared_trips}
		if request.method == "GET":
			
			query = request.GET.get('q')
			if query:
				context = search(all_shared_trips, query)
				print(context)
			
		all_trips = Trip.objects.filter(user=request.user)
		
		new_form_trips = NewTrip.objects.filter(user=request.user)
		loged_user = request.user
		context['all_trips'] = new_form_trips
		context['loged_user'] = loged_user
		if not loged_user.is_active:
			activate_key = ActivationKey.objects.get(user_id=loged_user.id)
			url="http://localhost:8000/organizer/activate/"+activate_key.key
			context['activate'] = url
		print(context)
		return render(request, 'organizer/index.html', context)
			
	
def detail(request, trip_id):	
	if not request.user.is_authenticated():
		all_shared_trips = Trip.objects.filter(shared=True)
	
		return render(request, 'organizer/details.html', {'trip' : trip})
		
	else:
		trip = get_object_or_404(Trip, pk=trip_id)
		hotels = Hotel.objects.all()
		loged_user = request.user
		if trip.user == request.user:
			return render(request, 'organizer/details.html', {'trip' : trip, "can_delete": True ,'loged_user': loged_user, 'hotels': hotels})
		else:
			return render(request, 'organizer/details.html', {'trip' : trip, 'loged_user': loged_user})
	
def new_detail(request, trip_id):	
	if not request.user.is_authenticated():
		trip = get_object_or_404(NewTrip, pk=trip_id)
		nodes = Node.objects.filter(trip=trip.pk)
		return render(request, 'organizer/new_details.html', {'trip' : trip, 'nodes': nodes})
		
	else:
		trip = get_object_or_404(NewTrip, pk=trip_id)
		nodes = Node.objects.filter(trip=trip.pk)
		types = NodeType.objects.all()
		loged_user = request.user
		if trip.user == request.user:
			return render(request, 'organizer/new_details.html', {'trip' : trip, "can_delete": True ,'loged_user': loged_user, 'nodes': nodes, 'types' : types})
		else:
			return render(request, 'organizer/new_details.html', {'trip' : trip, 'loged_user': loged_user, 'nodes': nodes})
			
def details2(request, trip_id):	
	if not request.user.is_authenticated():
		trip = get_object_or_404(NewTrip, pk=trip_id)
		nodes = Node.objects.filter(trip=trip.pk).order_by('sequance_in_trip')
		return render(request, 'organizer/details2.html', {'trip' : trip, 'nodes': nodes})
		
	else:
		trip = get_object_or_404(NewTrip, pk=trip_id)
		nodes = Node.objects.filter(trip=trip.pk).order_by('sequance_in_trip')
		types = NodeType.objects.all()
		loged_user = request.user
		if trip.user == request.user:
			return render(request, 'organizer/details2.html', {'trip' : trip, "can_delete": True ,'loged_user': loged_user, 'nodes': nodes, 'types' : types})
		else:
			return render(request, 'organizer/details2.html', {'trip' : trip, 'loged_user': loged_user, 'nodes': nodes})
	
	
def share(request, trip_id):
	trip = get_object_or_404(NewTrip, pk=trip_id)
	try:
		if trip.shared:
			trip.shared = False
		else:
			trip.shared = True
			trip.save()
	except (KeyError, NewTrip.DoesNotExist):
		return JsonResponse({'success': False})
	else:
		all_shared_trips = NewTrip.objects.filter(shared=True)
		html = render_to_string('organizer/index_items.html', {'all_shared_trips': all_shared_trips})
		return JsonResponse({'success': True, 'shared': html})
	
def date_change(request, trip_id):
	trip = get_object_or_404(Trip, pk=trip_id)
	
	if trip.shared is not True:
		trip.startDate =  datetime.strptime(request.POST['startDate'], '%m/%d/%Y')
		trip.endDate = datetime.strptime(request.POST['endDate'], '%m/%d/%Y')
		trip.save()
	return render(request, 'organizer/details.html', {'trip' : trip})
	
	
def hotel_change(request, trip_id):
	trip = get_object_or_404(Trip, pk=trip_id)
	if trip.shared is not True:
		trip.hotel = request.POST['hotel']
		trip.hotel_price = request.POST['hotel_price']
		trip.existing_hotel = Hotel.objects.get(id=request.POST['existing_hotel'])
		trip.save()
	
	return redirect(reverse('organizer:detail', kwargs={'trip_id' :   trip_id}), request)

	
def flight_change(request, trip_id):
	trip = get_object_or_404(Trip, pk=trip_id)
	if trip.shared is not True:
		trip.flight_no = request.POST['flight_no']
		trip.flight_price = request.POST['flight_price']
		trip.save()
	return render(request, 'organizer/details.html', {'trip' : trip})

def transport_change(request, trip_id):
	trip = get_object_or_404(Trip, pk=trip_id)
	if trip.shared is not True:
		trip.transport_company = request.POST['transport_company']
		trip.transport_price = request.POST['transport_price']
		trip.save()
	return redirect('organizer/details.html', request)

	

def add_node(request, trip_id):
	if not request.user.is_authenticated():
		trip = get_object_or_404(NewTrip, pk=trip_id)
		nodes = Node.objects.filter(trip=trip.pk)
		return render(request, 'organizer/new_details.html', {'trip' : trip, 'nodes': nodes})
	node = Node()
	node.trip = NewTrip.objects.get(id=trip_id)
	node.type = NodeType.objects.get(id=request.POST['type'])
	nodes = Node.objects.filter(trip=trip_id).order_by('-sequance_in_trip')
	if not nodes:
		node.sequance_in_trip = 0
	else:
		node.sequance_in_trip = nodes[0].sequance_in_trip + 1
	node.save()
	return redirect(reverse('organizer:detail', kwargs={'trip_id' :   trip_id}), request)
	
def insert_node(request, trip_id):
	if not request.user.is_authenticated():
		trip = get_object_or_404(NewTrip, pk=trip_id)
		nodes = Node.objects.filter(trip=trip.pk)
		return render(request, 'organizer/new_details.html', {'trip' : trip, 'nodes': nodes})
	
	next_node = Node.objects.get(id=request.POST['node_id'])
	if next_node is None:
		print('no such node')
		return redirect(reverse('organizer:detail', kwargs={'trip_id' :   trip_id}), request)
	sequance_in_trip = next_node.sequance_in_trip
	Node.objects.filter(sequance_in_trip__gte=sequance_in_trip).update(sequance_in_trip=F('sequance_in_trip') + 1 )
	
	node = Node()
	node.trip = NewTrip.objects.get(id=trip_id)
	node.type = NodeType.objects.get(id=request.POST['type'])
	node.sequance_in_trip = sequance_in_trip
	node.save()
	
	return redirect(reverse('organizer:detail', kwargs={'trip_id' :   trip_id}), request)
	
def add_flight(request, trip_id):
	if not request.user.is_authenticated():
		trip = get_object_or_404(NewTrip, pk=trip_id)
		nodes = Node.objects.filter(trip=trip.pk)
		return render(request, 'organizer/new_details.html', {'trip' : trip, 'nodes': nodes})
	node = Node()
	node.trip = NewTrip.objects.get(id=trip_id)
	node_id = request.POST['node_id']
	node.save()

organizer/templates/organizer/base.html
<!doctype>
<html>

	<head>
	
	
	<meta name="viewport" content="width=device-width">
	<title>{% block title%}Index{% endblock %}</title>

	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"  integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.css" />
	<link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'organizer/style.css' %}" />
	
	<style>
		
	</style>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
	<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
	<script src="{% static 'organizer/main.js' %}"></script>
	

	</head>
<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<!-- logo -->
			
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="{% url 'organizer:index' %}">Organizer</a>
			</div>
			<!-- items -->
			
			<div class="collapse navbar-collapse" id="topNavBar">
			{% if loged_user %}
				<ul class="nav navbar-nav">
					<li class="">
						<a href="{% url 'organizer:index' %}">
							<span class="glyphicon glyphicon-briefcase" area-hidden="true"></span>&nbsp;
							My Trips
						</a>
					</li>
					{% if activate %}
						<li class=" my-alert">
							<a class="my-alert" href="{{activate}}">
								Click Here To Activate Your Account
							</a>
						</li>
					{% endif %}
					
				</ul>

				<ul class="nav navbar-nav navbar-right" >
					<li>
						{% include 'organizer/search.html' %}
					</li>
					<li class="">
						<a href=" {% url 'organizer:create_trip' %} ">
							<span class="glyphicon glyphicon-plus" area-hidden="true"></span>&nbsp;
							Add Trip
						</a>
					</li>
					
					<li class="">
						<a href=" {% url 'organizer:logout_user' %} ">
							<span class="glyphicon glyphicon-off" area-hidden="true"></span>&nbsp;
							Logout
						</a>
					</li>
				</ul>
			{% else %}
				<ul class="nav navbar-nav navbar-right" >
					<li>
						{% include 'organizer/search.html' %}
					</li>
					<li class="">
						<a href=" {% url 'organizer:login_user' %} ">
							
							Login
						</a>
					</li>
					<li class="">
						<a  href=" {% url 'organizer:register' %} ">
							
							Register
						</a>
					</li>
				</ul>
			{% endif %}
			<ul class="nav navbar-nav">
				<li >
					<a onclick="addTripsToURL(this)" href=" {% url 'organizer:compare' %} ">
						Compare
					</a>
				</li>
			</ul>
			</div>
		</div>
	</nav>
	
	{% block body%}
	{% endblock%}
	
</body>
</html>

organizer/templates/organizer/error.html
{% extends 'organizer/base.html'%}

{% block title %}
	Index
{% endblock %}
{% load staticfiles %}
{% block body %}
	<h3>{{error}}</h3>
{% endblock %}

organizer/templates/organizer/flight_item.html
{% load staticfiles %}
<div class="flight item">
<div class="row">
	<div class="col-xs-1 insert-item">
		{% include 'organizer/insert.html' %}
	</div>
	<div class=" col-xs-offset-10 col-xs-1 delete-item">
		<form action="{% url 'organizer:node_delete' trip.id %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="node_id" value="{{ node.id }}">
			<button type="submit" class="btn btn-danger "/>
				<span class="glyphicon glyphicon-remove"></span>
			</button>
		</form>
	</div>
</div>
<div class="row">
	<form class="item-form flight" name="input" action="{% url 'organizer:node_edit_json' trip.id %}" method="post">
		{% csrf_token %}
		<input type="hidden" name="node_id" value="{{ node.id }}">
		<div class="col-xs-12 col-sm-5">
			<div><i class="btn glyphicon glyphicon-plane item-type-icon"></i></div>
			<h5 class="flight-number">Flight #</h5>
			
			<div class="flight-departure"><img src="{% static 'organizer/icons/departure.svg' %}" class="departure-icon" height="20" ></img>
				<h5>TakeOff Time</h5>
				<input size="5" class="date form-control startDate" name="startDate" type="text" value="{{ node.startDate|date:'m/d/Y' }}">
				<p class="airport">Departure Airport</p>
				
				<div class="coordinates departure-coor">
					<div>Coordinates</div>
					<div class="text-danger small"></div>
					<input type="text" class="form-control coordinate departure_lat" value="{{node.departure_lat}}" name="departure_lat"></input>
					<input type="text" class="form-control coordinate departure_lng" value="{{node.departure_lng}}" name="departure_lng"></input>
				</div>
			</div >
			<div class="flight-arrival">
				<img src="{% static 'organizer/icons/arrival.svg' %}" class="departure-icon" height="20" ></img>
				<h5>Landing Time</h5>
				<div class="text-center">
				<input size="5" class="date input-price form-control endDate" name="endDate" type="text" value="{{ node.endDate|date:'m/d/Y' }}">
				
				</div>
				<p class="airport">Arrival Airport</p>
				<div class="coordinates arrival-coor">
					<div>Coordinates</div>
					<input type="text" class="form-control coordinate" value="{{node.arrival_lat}}" name="arrival_lat"></input>
					<input type="text" class="form-control coordinate" value="{{node.arrival_lng}}" name="arrival_lng"></input>
				</div>
			</div>
			<div class="text-center clear-float">
				
			</div>
		</div>
		<div class="col-xs-12 col-sm-4">
			<h4 class="list-group-item-heading"> Free Text </h4>
			<textarea name="text"  class=" form-control list-group-item-text free-text ">{{node.text}}</textarea>
		</div>
		<div class="col-xs-12 col-sm-3 text-center">
			<div>
				<h2><input class="form-control price input-price" type="text" name="price" value="{{ node.price }}"/><span class="currency">$<span></h2>
			</div>
			<h2><span class="total_time"></span><span class="days" >Days</span></h2>
			<input type="submit" value="Save" class="btn btn-primary btn-lg  btn-block btn-save"/>
		</div>
		<div class="clearfix"></div>
	</form>
</div>
</div>

organizer/templates/organizer/hotel_item.html
{% load staticfiles %}
<div class="hotel item">
<div class="row">
	<div class="col-xs-1 insert-item">
		{% include 'organizer/insert.html' %}
	</div>
	<div class=" col-xs-offset-10 col-xs-1 delete-item">
		<form action="{% url 'organizer:node_delete' trip.id %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="node_id" value="{{ node.id }}">
			<button type="submit" class="btn btn-danger "/>
				<span class="glyphicon glyphicon-remove"></span>
			</button>
		</form>
	</div>
</div>
<div class="row">
	
		<form class="item-form" name="input" action="{% url 'organizer:node_edit_json' trip.id %}" method="post">
			{% csrf_token %}
			<input type="hidden" name="node_id" value="{{ node.id }}">
			<div class="col-xs-12 col-sm-5">
			<div><img src=" {% static 'organizer/icons/hotel.svg' %} " class="item-type-icon" height="100" ></img></div>
			<h5 class="hotel-name">Hotel Name</h5>
			<h5>Hotel Address</h5>
			
			<div class="coordinates departure-coor">
				<div>Coordinates</div>
				<input type="text" class="form-control coordinate" value="{{node.lat}}" name="lat"></input>
				<input type="text" class="form-control coordinate" value="{{node.lng}}" name="lng"></input>
			</div>
			<span class="dates">
				<div class="col-xs-12 col-sm-6 hotel-checkin "><span></span>
					<label>CheckIn Time</label>
					<i class="btn glyphicon glyphicon-calendar flight"></i><input size="5" class="date form-control start_date" name="startDate" type="text" value="{{ node.startDate|date:'m/d/Y' }}">
					
				</div>
				<div class="col-xs-12 col-sm-6 hotel-checkout end_date">
					<label>CheckOut Time</label>
					<div class="btn-group" role="group" aria-label="...">
					<i class="btn glyphicon glyphicon-calendar flight"></i><input size="5" class="date input-price form-control" name="endDate" type="text" value="{{ node.endDate|date:'m/d/Y' }}">
					</div>
					
				</div>
			</span>
			<div class="text-center clear-float">
				
			</div>
			</div>
			<div class="col-xs-12 col-sm-4">
				<h4 class="list-group-item-heading"> Free Text </h4>
				<textarea name="text"  class=" form-control list-group-item-text free-text ">{{node.text}}</textarea>
			</div>
			<div class="col-xs-12 col-sm-3 text-center">
				<h2><input class="form-control price input-price" type="text" name="price" value="{{ node.price }}"/><span class="currency">$<span></h2>
				<h2><span class="total_time"></span><span class="days" >Days</span></h2>
				
				
				<input type="submit" value="Save" class="btn btn-primary btn-lg  btn-block btn-save"/>
			</div>
			<div class="clearfix"></div>
		</form>
	</div>
</div>

organizer/templates/organizer/insert.html
<div class = "btn-group">
	<button type = "button" class = "btn btn-success dropdown-toggle" data-toggle = "dropdown">
		Insert 
		<span class = "caret"></span>
	</button>
   
	<ul class = "dropdown-menu" role = "menu">
		<li>
			<form action="{% url 'organizer:insert_node' trip.id %}" method="post" style="display: inline;">
				{% csrf_token %}
				<input type="hidden" name="type" value="1" />
				<input type="hidden" name="node_id" value="{{ node.id }}">
				<button  type="submit" class="btn btn-success ">
				<span class="glyphicon glyphicon-plus"></span>&nbsp; Flight
				</button>
			</form>
		</li>
		<li>
			<form action="{% url 'organizer:insert_node' trip.id %}" method="post" style="display: inline;">
				{% csrf_token %}
				<input type="hidden" name="type" value="2" />
				<input type="hidden" name="node_id" value="{{ node.id }}">
				<button  type="submit" class="btn btn-success ">
				<span class="glyphicon glyphicon-plus"></span>&nbsp; Hotel
				</button>
			</form>
		</li>
		<li>
			<form action="{% url 'organizer:insert_node' trip.id %}" method="post" style="display: inline;">
				{% csrf_token %}
				<input type="hidden" name="type" value="3" />
				<input type="hidden" name="node_id" value="{{ node.id }}">
				<button  type="submit" class="btn btn-success ">
				<span class="glyphicon glyphicon-plus"></span>&nbsp;  Transport
				</button>
			</form>
		</li>
	</ul>
</div>

organizer/templates/organizer/login.html
{% extends 'organizer/base.html'%}

{% block title %}
	Index
{% endblock %}

{% block body %}
<div class="container-fluid ">

    <div class="row">
        <div class=" col-sm-12">
            <div class="panel panel-default  auto-margin">
                <div class="panel-body  ">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'organizer:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'organizer:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

organizer/templates/organizer/search.html
<form class="navbar-form" role="search" action="{% url 'organizer:index' %}">
	<div class="input-group">
		{% if search_value %}
			<input type="text" class="form-control" value="{{search_value}}" name="q">
		{% else %}
			<input type="text" class="form-control" placeholder="Search Shared Trips" name="q">
		{% endif %}
		<div class="input-group-btn">
			<button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
		</div>
	</div>
</form>